namespace InventoryDashboard.Application.DTOs;

public record VehicleDto(
    Guid Id,
    string Make,
    string Model,
    int Year,
    string Vin,
    decimal Price,
    int Quantity,
    bool IsDisabled,
    string? Note,
    DateTime DateAddedToInventory,
    int DaysInInventory,
    bool IsAgingStock,
    bool IsLowStock,
    string Color,
    string ExteriorColor,
    string InteriorColor,
    int Mileage,
    string FuelType,
    string Transmission,
    string Engine,
    string BodyType,
    string Description,
    string? ImageUrl);

public record VehicleDetailDto(
    Guid Id,
    string Make,
    string Model,
    int Year,
    string Vin,
    decimal Price,
    int Quantity,
    bool IsDisabled,
    string? Note,
    DateTime DateAddedToInventory,
    int DaysInInventory,
    bool IsAgingStock,
    bool IsLowStock,
    string Color,
    string ExteriorColor,
    string InteriorColor,
    int Mileage,
    string FuelType,
    string Transmission,
    string Engine,
    string BodyType,
    string Description,
    string? ImageUrl,
    DateTime CreatedAt,
    DateTime? UpdatedAt);

public record CreateVehicleDto(
    string Make,
    string Model,
    int Year,
    string Vin,
    decimal Price,
    int Quantity,
    string? Note,
    DateTime? DateAddedToInventory,
    string Color,
    string ExteriorColor,
    string InteriorColor,
    int Mileage,
    string FuelType,
    string Transmission,
    string Engine,
    string BodyType,
    string Description,
    string? ImageUrl);

public record UpdateVehicleDto(
    string Make,
    string Model,
    int Year,
    string Vin,
    decimal Price,
    int Quantity,
    string? Note,
    DateTime DateAddedToInventory,
    string Color,
    string ExteriorColor,
    string InteriorColor,
    int Mileage,
    string FuelType,
    string Transmission,
    string Engine,
    string BodyType,
    string Description,
    string? ImageUrl);

public record VehicleQueryDto(
    int Page = 1,
    int PageSize = 10,
    string? Search = null,
    string? Make = null,
    string? Model = null,
    int? MinAgeDays = null,
    int? MaxAgeDays = null,
    bool? AgingOnly = null);
